project:
  type: book

book:
  title: "制御理論ノート"
  author: "Mr. Hoge"
  date: "11/09/2024"
  chapters:
    - index.qmd
    - src/control.ipynb
    - src/simulation.ipynb

bibliography: references.bib

format:
  html:
    theme: cosmo
