project:
  type: book

book:
  title: "Control"
  author: "Mr. Hoge"
  date: "11/1/2024"
  chapters:
    - index.qmd
    - notebook/test.ipynb

bibliography: references.bib

format:
  html:
    theme: cosmo
